name: Documentation

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout Codex
        uses: actions/checkout@v2
        with:
          repository: shamazmazum/codex
          path: ~/lisp/codex
      - name: Checkout docparser
        uses: actions/checkout@v2
        with:
          repository: shamazmazum/docparser
          path: ~/lisp/docparser
      - name: Install roswell
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install Ultralisp
        run: |
          ros -e '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)'
      - name: Get ASDF
        run: |
          wget https://common-lisp.net/project/asdf/archives/asdf.lisp
          cp asdf.lisp $HOME/.roswell/lisp/quicklisp
          sed -i.bak -e 's/(try (require "asdf"))// ' $HOME/.roswell/lisp/quicklisp/setup.lisp
      - name: Build documentation
        run: |
          ros -s codex -e '(codex:document :pure-spatial-trees)'
      - name: Deploy to GH pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/pure-spatial-trees/html
